import { prisma } from '../lib/prisma';

export class AnalyticsService {
    /**
     * Calculates total operational cost generated by a specific vehicle.
     * Total Operational Cost = Fuel Logs + Maintenance Logs + External Trip Expenses
     */
    public static async getVehicleTotalOperationalCost(vehicleId: string): Promise<number> {
        const expensesAgg = await prisma.expense.aggregate({
            where: { vehicleId },
            _sum: { amount: true },
        });

        const maintenanceAgg = await prisma.maintenanceLog.aggregate({
            where: { vehicleId },
            _sum: { cost: true },
        });

        const fuelAgg = await prisma.fuelLog.aggregate({
            where: { vehicleId },
            _sum: { cost: true },
        });

        const expensesTotal = expensesAgg._sum.amount || 0;
        const maintenanceTotal = maintenanceAgg._sum.cost || 0;
        const fuelTotal = fuelAgg._sum.cost || 0;

        return expensesTotal + maintenanceTotal + fuelTotal;
    }

    /**
     * Calculates Cost Per KM using recorded distances generated inside dispatch loops.
     */
    public static async getVehicleCostPerKm(vehicleId: string): Promise<number> {
        const totalCost = await this.getVehicleTotalOperationalCost(vehicleId);

        const tripAgg = await prisma.trip.aggregate({
            where: { vehicleId, distanceKm: { not: null } },
            _sum: { distanceKm: true },
        });

        const totalKm = tripAgg._sum.distanceKm || 0;

        if (totalKm === 0) return 0; // Prevent division by zero

        return Number((totalCost / totalKm).toFixed(2));
    }
}
